### ISSUE TITLE
发送事件给本Fragment，订阅方法会执行两次

### ISSUE THREAD

**Issue by tzrgaga** [bboyfeiyu/AndroidEventBus#13]
![image](https://cloud.githubusercontent.com/assets/9652722/7836681/a319c77c-04b4-11e5-80c4-0a303d03a328.png)
我在异步线程中发送事件

在本类中订阅事件
![image](https://cloud.githubusercontent.com/assets/9652722/7836698/cf9694b0-04b4-11e5-8454-50fa3dd5ef23.png)

这个订阅方法会连续执行两次，能帮我解决下这个问题吗？

**Comment by bboyfeiyu** [comment]
@tzrgaga demo中有从异步线程发送事件的例子，你可以看看。或者你新建一个简单的工程测试一下是否有问题。

**Comment by bboyfeiyu** [comment]
@tzrgaga 建了一个demo测试没有问题，你那边自己查一下原因吧。:)

**Comment by tzrgaga** [comment]
刚刚建了个demo试了下，还是会出现连续两次调用这种问题，把订阅方法写到别的activity也是调用两次，异步线程发送事件应该是这样写的吧，现在感觉很疑惑。

**Comment by bboyfeiyu** [comment]
Demo发来~

在 2015年5月28日 下午2:22，tzrgaga <notifications@github.com>写道：
