### ISSUE TITLE
post的event为基本数据类型时Subscriber接收不到

### ISSUE THREAD

**Issue by Ydcool** [bboyfeiyu/AndroidEventBus#15]
只有将event封装到对象的post事件能接收到。
> e.g
<pre>
        EventBus.getDefault().post(
                   Long.valueOf(SystemClock.elapsedRealtime()),   //works
//                 SystemClock.elapsedRealtime(),                          //not work
                   Constants.EVENT_TIMER_UPDATE);
</pre>

**Comment by wurensen** [comment]
什么版本？最新版本post事件类型为基本数据类型或对象类型，订阅函数为基本数据类型或对象类型都能正常接收。

**Comment by YdCodePlay** [comment]
@wurensen 版本1.0.4，应该是最新的吧？
又新建了一个project测试，确实有问题：
* 在Service中post事件为byte,short,long,char时不能接收
* int,float,double,boolean 可以接收
* 转为对象类型后都可以接收

**Comment by Ydcool** [comment]
找到原因了，不是BUG，低级错误。。基本类型做参数时虽然生命的变量为该类型，但其数值不明确，在自动装箱的时候不一定会转换为想要的包装类，导致匹配不到Subscriber
> e.g
<pre>
long value = 1000;   //wrong
long value = 1000L; //right
</pre>

**Comment by bboyfeiyu** [comment]
公司项目吗？


From Meizu MX4

-------- Original message --------
Sender: Ydcool <notifications@github.com>
Time: Thu 6/4 23:19
To: bboyfeiyu/AndroidEventBus <AndroidEventBus@noreply.github.com>
 Subject: Re: [AndroidEventBus] post的event为基本数据类型时Subscriber接收不到 (#15)

**Comment by Ydcool** [comment]
@bboyfeiyu 是的
