### ISSUE TITLE
关于unregister是否调用的问题(1.0.4 )

### ISSUE THREAD

**Issue by lixi0912** [bboyfeiyu/AndroidEventBus#16]
我在LoginActivity注册了User实体类的回调事件(当接收到User实体类时,则认为登录成功,在其他页面接收到的时候,则刷新当前页面),LoginActivity在接收到User之后,弹出Toast告知用户已经登录成功,并且finish掉自己.期望LoginActivity在onDestroy后,能即时的注销回调,不再接收User事件.然而
这时候有可能出现Subscriber还没有被回收的情况.出现再次触发了已经onDestroy的LoginActivity..
不符合初期的期望,...这不禁让我有些疑惑.当Activity的onDestroy执行之后,Subscriber什么时机会被系统回收呢? 是否又会因此影响到之前的代码逻辑,以及unregister定位于过时方法是否合理?  
 
小子的代码不漂亮,如果有时间请多多指教~

**Comment by bboyfeiyu** [comment]
@lixi0912 使用unregister进行注销，unregister在下次更新将去除deprecated注解。

**Comment by lixi0912** [comment]
@bboyfeiyu 已经使用unregister注销 不胜感激

**Comment by bboyfeiyu** [comment]
@lixi0912 已经更新了，可以帮测试一下。另外你们公司的产品上线了么 ？

**Comment by lixi0912** [comment]
@bboyfeiyu  好的,这个版本还没有

**Comment by zijianwang90** [comment]
现在把前面所有删掉的unregister又都加回来了
