### ISSUE TITLE
Android Studio 能否 用Gradle模式呢

### ISSUE THREAD

**Issue by ikkyu0319** [bboyfeiyu/AndroidEventBus#22]
现在 主流 都是 Android Studio + Gradle了，Maven 真的 不太会用~~

**Comment by ikkyu0319** [comment]
Android Studio 导入工程，运行不了~。。。。。

**Comment by bboyfeiyu** [comment]
集成方式不是有gradle么

**Comment by ikkyu0319** [comment]
刚发现有个 AS分之，master分之，貌似，不可以吧~~
