### ISSUE TITLE
可否建个QQ群什么的，方便用户交流。。

### ISSUE THREAD

**Issue by zhouyang-cn** [bboyfeiyu/AndroidEventBus#24]
我之前一直在用xutils，他们建了个QQ群，遇到问题了，或者有什么不懂的，都可以直接在群里交流，方便快捷。这样还有利于你这个库的推广。好东西，大家肯定会支持的。。

**Comment by bboyfeiyu** [comment]
可以，我新建一个吧。多谢建议

在 2015年8月14日 上午11:14，zhouyang <notifications@github.com>写道：

**Comment by bboyfeiyu** [comment]
@zhouyang-cn 

群名称：AndroidEventBus技术交流群
群   号：312090070
