### ISSUE TITLE
跟EventBus有什么区别吗？

### ISSUE THREAD

**Issue by xu6148152** [bboyfeiyu/AndroidEventBus#5]
功能上或者原理上。相对来说EventBus已经算是比较成熟了。

**Comment by bboyfeiyu** [comment]
readme上有写，你先看一看吧。如果比较追求效率，可以用EventBus，如果觉得EventBus不太好用，可以是尝试用我这个。

**Comment by Jakevin** [comment]
我兩個都會使用，因為多了Tag機制讓我在post上安心不少
EventBus.post(Bundle bundle)
因為你無法知道有多少準備接收的Bundle有多少，導致程式上的管理出現非常嚴重的瑕疵

透過Tag 可以很清楚知道Bundle多少發送的點，多少接收的點

相當清楚！

**Comment by bboyfeiyu** [comment]
是的，当初发布这个框架也是因为原来的EventBus的一些局限，各有优缺点，按需选择就好。
